### PR TITLE
making bemobile to work on haiku.

### PR DESCRIPTION
**Pull request by abt2804**
Now it builds just fine :)

### CODE REVIEW

**Comment by ytmytm** [comment]
If I understand that right it now uses system-provided libsanta but headers provided in this project. In this case, should the local headers be removed too to use system-provided ones?

**Comment by abt2804** [comment]
@ytmytm AFAIK this uses headers specifically for this application.
Or maybe you want to ask something else.

**Comment by ytmytm** [comment]
I'm not familar with current Haiku state. What I mean is that I included libsanta because it was not a standard part of BeOS, so I included both library and headers. But if Haiku provides libsanta as part of standard distribution it should also provide both library and headers. In this case if a program (BeMobile) links against libsanta provided by OS  it should also use headers for that library provided by OS - then a local project copy is not needed anymore.

**Comment by abt2804** [comment]
> I'm not familar with current Haiku state. What I mean is that I included libsanta because it was not a standard part of BeOS, so I included both library and headers. But if Haiku provides libsanta as part of standard distribution it should also provide both library and headers. In this case if a program (BeMobile) links against libsanta provided by OS it should also use headers for that library provided by OS - then a local project copy is not needed anymore.

No, libsanta isn't come by default but you can download it.

**Pull request merged**
